//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_SchemaFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_gender { get; set; }
        public Nullable<System.DateTime> employee_date_of_birth { get; set; }
        public string employment_type { get; set; }
        public Nullable<int> salary { get; set; }
        public string partner_name { get; set; }
        public Nullable<int> department_id { get; set; }
    
        public virtual department department { get; set; }
    }
}
